---
abstract: unknown
author:
  - 'Marcin Junczys-Dowmunt <marcinj@>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CLD2
no_index:
  directory:
    - t
    - inc
requires:
  Inline: '0.44'
version: '0.10'
